// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	user2 "ship/internal/biz/user"
	"ship/internal/dao"
	"ship/internal/dao/user"
	"ship/internal/service"
	user3 "ship/internal/service/user"
)

// Injectors from wire.go:

func initApp() (*service.AllService, func(), error) {
	dbClient := dao.NewDbClient()
	repoUser := &user.RepoUser{
		Handle: dbClient,
	}
	bizUser := &user2.BizUser{
		UserDao: repoUser,
	}
	serviceUser := &user3.ServiceUser{
		BizUser: bizUser,
	}
	allService := &service.AllService{
		UserSrv: serviceUser,
	}
	return allService, func() {
	}, nil
}
